### ISSUE TITLE
Expected cyanaudit files not present in module distribution

### ISSUE THREAD

**Issue by esheffield** [EOSIO/demux-js-postgres#24]
This seems to be a packaging error. When attempting to run the MigrationRunner.setup() routine, the following error occurs:

```
Unable to setup / migrate database: QueryFileError {
    message: "ENOENT: no such file or directory, open '<path_to_repo>/demux/node_modules/demux-postgres/dist/cyanaudit/cyanaudit--2.2.0.sql'"
    options: {"debug":false,"minify":true,"compress":false,"noWarnings":true,"params":{"schema":""}}
    file: "<path_to_repo>/demux/node_modules/demux-postgres/dist/cyanaudit/cyanaudit--2.2.0.sql"
}
```

Looking down the node_modules/demux-postgres/dist path, there is no cyanaudit directory.  Not sure how release-it works, but if it works from the dist directory, `yarn compile` only puts the .d.ts and .js files there. The cyanaudit files don't get copied over.

**Comment by flux627** [comment]
Resolved via #25
